FROM nnurphy/buildah:podmanbuildbase
RUN set -eux; \
	sed -i 's/dl-cdn.alpinelinux.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apk/repositories; \
	apk add --update --no-cache automake autoconf meson ninja clang eudev-dev
ARG LIBFUSE_VERSION=fuse-3.5.0
RUN git clone --branch=${LIBFUSE_VERSION} https://github.com/libfuse/libfuse /libfuse
WORKDIR /libfuse
RUN set -eux; \
	mkdir build; \
	cd build; \
	LDFLAGS="-lpthread" meson --prefix /usr -D default_library=static ..; \
	ninja; \
	ninja install
# v0.3 + musl compat fix
ARG FUSEOVERLAYFS_VERSION=2cbd1c4a2d3ab06c4e39276363c74c6a9c62c0fe
RUN set -eux; \
	git clone https://github.com/containers/fuse-overlayfs /fuse-overlayfs; \
	cd /fuse-overlayfs; \
	git checkout "${FUSEOVERLAYFS_VERSION}"; \
	sh autogen.sh; \
	LIBS="-ldl" LDFLAGS="-static" ./configure --prefix /usr; \
	make; \
	make install; \
	fuse-overlayfs --help >/dev/null

